import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./../styles/globals.css"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import Image from "next/image";
import Box from '@mui/material/Box'
import { ImageContainer } from "@/components/ImageContainer";
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/styles/theme";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={nunito.className}>
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box
              sx={{
                minHeight: '100vh',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center'
              }}
            >
              <ImageContainer>
                <Image
                  src='/woovi-logo.png'
                  alt='woovi-logo'
                  width={120}
                  height={37}
                />
              </ImageContainer>
              {children}
              <ImageContainer>
                <Image
                  src='/footer.png'
                  alt='rodape'
                  width={270}
                  height={22}
                />
              </ImageContainer>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
